OHDSI/dbt-synthea

models/staging/synthea/stg_synthea__conditions.sql
models/staging/synthea/stg_synthea__imaging_studies.sql
models/staging/synthea/stg_synthea__immunizations.sql
models/staging/synthea/stg_synthea__medications.sql
models/staging/synthea/stg_synthea__observations.sql
models/staging/synthea/stg_synthea__organizations.sql
models/staging/synthea/stg_synthea__payer_transitions.sql
models/staging/synthea/stg_synthea__payers.sql
models/staging/synthea/stg_synthea__procedures.sql
models/staging/synthea/stg_synthea__providers.sql
models/staging/synthea/stg_synthea__supplies.sql

@katy-sadowski I thought it would be easier to get some additional stage models into your branch (incorporating your macro and pre commit requirements) as opposed to a PR directly into main (with those files copied in anyway).
- The additional models are conditions, imaging_studies, immunizations, medications, observations, organizations, payer_transitions, payers, procedures, providers and supplies.
-  The additional models are able to run and pass most tests (with some claims/claims_transaction fk issues on member_id and payer_id) which seem to be FK issues with the seed data as opposed to structural issues. If I goofed something up there and its actually structural let me know :)

Add additional stg models

---

.pre-commit-config.yaml
.sqlfluff
.sqlfluffignore
README.md
STYLE_GUIDE.md
dbt_project.yml
macros/lowercase_columns.sql
models/marts/omop/person.sql
models/staging/synthea/_synthea__models.yml
models/staging/synthea/stg_synthea__allergies.sql
models/staging/synthea/stg_synthea__careplans.sql
models/staging/synthea/stg_synthea__claims.sql
models/staging/synthea/stg_synthea__claims_transactions.sql
models/staging/synthea/stg_synthea__conditions.sql
models/staging/synthea/stg_synthea__devices.sql
models/staging/synthea/stg_synthea__encounters.sql
models/staging/synthea/stg_synthea__imaging_studies.sql
models/staging/synthea/stg_synthea__immunizations.sql
models/staging/synthea/stg_synthea__medications.sql
models/staging/synthea/stg_synthea__observations.sql
models/staging/synthea/stg_synthea__organizations.sql
models/staging/synthea/stg_synthea__patients.sql
models/staging/synthea/stg_synthea__payer_transitions.sql
models/staging/synthea/stg_synthea__payers.sql
models/staging/synthea/stg_synthea__procedures.sql
models/staging/synthea/stg_synthea__providers.sql
models/staging/synthea/stg_synthea__supplies.sql

- Adds stg models for careplans, claims_transactions, claims, devices, and encounters (#11 , #12, #13, #15, #16)
- Updates column names in person stg model to remove unnecessary person_ prefix from some columns. Only need tablename prefix for potentially ambiguous column names (i.e., used in other source tables)
- Adds initial style guide (#8)
- Adds SQLFluff (#7) and related documentation
- Creates macro for lowercasing column names
Also: #32

Add more models, fix column naming, add style guide, add SQLFluff

---

README.md
dbt_project.yml
models/omop/care_site.sql
models/omop/location.sql
models/staging/map/_map__models.yml
models/staging/map/_map__sources.yml
models/staging/map/stg_map__states.sql
models/staging/vocabulary/_vocabulary__model.yml
models/staging/vocabulary/_vocabulary__sources.yml
models/staging/vocabulary/stg_vocabulary__source_to_concept_map.sql
seeds/map/states.csv
seeds/vocabulary/source_to_concept_map.csv

We were missing source_to_concept_map (empty), care_site, and location. This PR adds the models for those tables - mirroring SQL from ETL-Synthea.  The state mapper is added as a seed file :)

Add 3 missing tables

---

models/staging/synthea/_synthea__models.yml

- test fails because of bad synthea output / invalid docs
- issue upstream of this repo (synthetichealth/synthea)
- neither `patient_insurance_id` nor `member_id` is used at any point other than this test
------
Resolves #50

fix: remove broken relationship test

---

scripts/python/generate_dbt_yaml.py

This PR introduces a script to generate DBT docs and tests from the CDM definition (from HTML documentation).
Includes:
- `data_type`s for target concepts
- column documentation
- table descriptions
This output works in `dbt docs`.
- Some data in the OMOP docs are wrong (upstream of this PR, will see if fixable at some point)
- Some odd/atypical characters used - e.g. ’ (U+2019 RIGHT SINGLE QUOTATION MARK) - but is handled fine by dbt docs

feat: Add script to generate dbt YAML files from OMOP CDM HTML docs

---

models/omop/concept.sql
models/omop/concept_ancestor.sql
models/omop/concept_class.sql
models/omop/concept_relationship.sql
models/omop/concept_synonym.sql
models/omop/domain.sql
models/omop/drug_strength.sql
models/omop/relationship.sql
models/omop/source_to_concept_map.sql
models/omop/vocabulary.sql

Vocab models now always build, for both seed source and BYOD.  See: https://github.com/OHDSI/dbt-synthea/pull/61#issuecomment-2381439006

Remove conditional build of vocab models

---

models/intermediate/int__person.sql
models/omop/visit_detail.sql
models/omop/visit_occurrence.sql
seeds/vocabulary/_sources.yml

This PR fixes a handful of issues that cause postgres to fail running the project.
These issues were all around type casting, given the empty seed files would result to everything being cast as integrers, and nulls without types being treated as text types. Duckdb is much more forgiving!
For now I have:
- Added explicit seed types as needed (only on files where the seed is blank)
- Explicitly cast `NULL`s to `INTEGER` types for ids

fix: use explicit seed types or null type casts where necessary for postgres

---

.github/workflows/generate-docs.yml

This PR adds automatic dbt docs generation for the `dbt-synthea` project.
The docs are a nice place to start for those not used to either dbt / OMOP to explore the models/DAG/etc (IMHO - feel free to disagree!); is easier for us to point people to our project!
This approach requires little/no effort of maintainers once setup.
- runs when a relevant file in github has been modified in the main branch (as per paths filter)
- installs python + requirements (caches as possible)
- uses duckdb rendering of the project (lighterweight/friendly flavour of sql compared to others)
- uploads to GitHub pages (this needs to be enabled by an admin)
- Enable pages (if approved/agreed as useful)
- Add other docs to make prettier/complete - e.g. an …

feat: Add workflow to generate DBT documentation and deploy to GitHub Pages

---

.github/workflows/generate-docs.yml

- causes dbt docs to pickup materialised column data types #75
- arguably testing is over the top but duckdb is so fast there is little downside!

fix: build project prior to `dbt docs generate`

---

models/omop/drug_era.sql

- various sql engines do not allow interval extraction from delta (as deltas are passed as numeric types); concretely: snowflake, likely others
- use the dbt standard datediff/dateadd macro to open up possibility to other sql engines
- arguably more idiomatic
- bring in line with other recent changes by @katy-sadowski

refactor: use `datediff`/`dateadd` macro

---

macros/macros.yml
macros/safe_hash.sql
models/intermediate/int__locations.sql
models/intermediate/int__person.sql
models/omop/care_site.sql
models/omop/location.sql

This PR refactors the existing location model to have a valid PK to allow referencing from the `patient` and `care_site` tables. Previously the `location` table was orphaned and had duplicate entries.
The new referencing works by using a variation of address and city as a natural key to join on from other models.
---
I have some ongoing thoughts/issues:
- We might want to join on more to prevent this in the future  
There may be a far slicker approach to this but this is the best I can see for now! Happy to hear other's thoughts

refactor: build location model properly using patient and organization as a source

---

models/omop/location.sql
models/omop/provider.sql

This PR cleans up code imported from upstream OHDSI/SyntheaETL SQL code, where models can produce non-deterministic output for `location` and `provider` tables.
For both tables, output is now ordered by:
- state
- city
- zip
- patient/provider id
Perhaps this is too complicated, open to other ideas! I think this is somewhat more logical than doing: `city > state > zip > _id`, but may not be correct to US-centric norms

refactor: use determinisitic provider id

---

models/staging/synthea/_synthea__models.yml
seeds/synthea/_sources.yml

- `conditions` >> DESCRIPTION column not declared
-  multiple columns declared in synthea staging models that are not used in dbt-synthea
Loosely related to #101 #98

refactor: complete metadata for sources, remove unused yml column metadata 

---

dbt_project.yml
macros/regexp_like.sql
models/omop/measurement.sql
seeds/synthea/_sources.yml

This PR adds support for snowflake as a backend through various steps.
- Correct the declaration of the `Id` column across multiple seed files
- Add a new `regexp_like` macro for Snowflake, and...
- Refactor the measurement model to utilize this new macro. 
- Enable quoting of columns for Snowflake compatibility.

Fix column declaration and enhance regexp_like support for Snowflake

---

models/staging/synthea/_synthea__models.yml

This test should be enforced in theory, but:
- This model is not used downstream at all
- Due to a bug in Synthea duplicate imaging studies are generated synthetichealth/synthea#1545
Relax until fixed if needed for future work.

fix: remove imaging_studies > imaging_id unique test

---

.gitignore
README.md
models/intermediate/int__encounters.sql
models/intermediate/int__er_visits.sql
models/intermediate/int__ip_visits.sql
models/intermediate/int__op_visits.sql
models/intermediate/int__visit_detail.sql
models/intermediate/int__visits.sql
models/omop/death.sql
models/omop/visit_occurrence.sql
models/staging/synthea/stg_synthea__encounters.sql

Fixes #118 and #119 
There were 2 separate issues leading to PK duplication in PROCEDURE_OCCURRENCE:
- Something was messed up in the inpatient visit rollup logic
- There are duplicated encounter IDs in the source Synthea tables (a known bug)
For the first, I did a deep review of the IP rollup logic and fixed some issues with it.  I left a lot of comments because until now I didn't fully understand what it was doing (this came from ETL-Synthea).  I figure my comments may help others who want to understand or need to debug.
For the second, my solution was to remove these encounters from the project altogether.  Since there are other Synthea tables with foreign keys to the encounters table, I think this is the only way to handle the issue - I think it's better to lose the data than to …

Fix test failures

---

scripts/python/generate_dbt_yaml.py
scripts/python/generate_vocab_shard.py
scripts/python/get_csv_filepaths.py
scripts/python/shard_to_seeds.py

- Changed from using os path and directory functions to using pathlib's Path.
- Added type checking.
- Moved some logic to list/dict comprehension. We can expand this again if you feel it just makes it more difficult to read.
- Again changed to using Path.
- Added typing.
- Cast and type return values from duckdb.
- Separated the list creation and csv creation steps.
- Uses Path.
- Added type hints.
- Changed some of the SQL queries to keep the list processes inside duckdb. Previously we were requesting information, cleaning it, putting it into a list. Then adding that list back into a duckdb table. The new queries should do this within duckdb.
(duckdb build and building without using seeds ran after this change, and I was able to use this script on the resulting DB. But I think my data …

Added typing to and refactored the four python scripts. See Description.

---

dbt_project.yml
macros/timestamptz_to_naive.sql
models/omop/_models/cdm_source.yml
models/omop/_models/concept_ancestor.yml
models/omop/_models/concept_synonym.yml
models/omop/_models/observation.yml
models/omop/_models/relationship.yml
models/omop/_models/visit_detail.yml
models/staging/synthea/stg_synthea__claims.sql
models/staging/synthea/stg_synthea__claims_transactions.sql
models/staging/synthea/stg_synthea__devices.sql
models/staging/synthea/stg_synthea__encounters.sql
models/staging/synthea/stg_synthea__imaging_studies.sql
models/staging/synthea/stg_synthea__immunizations.sql
models/staging/synthea/stg_synthea__medications.sql
models/staging/synthea/stg_synthea__observations.sql
models/staging/synthea/stg_synthea__payer_transitions.sql
models/staging/synthea/stg_synthea__procedures.sql

Fixes #126 
- Adds 'timestamptz_to_naive' macro (created by katie).
- In staging models casts timestamptz columns to timestamp in UTC timezone.
- Where necessary adds an extra cte layer to staging models to ensure 'date' columns are based on the UTC timestamp.

Fix for duckdb 1.3

---

models/omop/metadata.sql
models/omop/note_nlp.sql
models/staging/synthea/stg_synthea__allergies.sql
models/staging/synthea/stg_synthea__careplans.sql
models/staging/synthea/stg_synthea__claims_transactions.sql
models/staging/synthea/stg_synthea__conditions.sql
models/staging/synthea/stg_synthea__devices.sql
models/staging/synthea/stg_synthea__encounters.sql
models/staging/synthea/stg_synthea__imaging_studies.sql
models/staging/synthea/stg_synthea__immunizations.sql
models/staging/synthea/stg_synthea__medications.sql
models/staging/synthea/stg_synthea__observations.sql
models/staging/synthea/stg_synthea__organizations.sql
models/staging/synthea/stg_synthea__patients.sql
models/staging/synthea/stg_synthea__payers.sql
models/staging/synthea/stg_synthea__procedures.sql
models/staging/synthea/stg_synthea__providers.sql
models/staging/synthea/stg_synthea__supplies.sql
seeds/synthea/_sources.yml

Replaced hardcoded double quotes around SQL identifiers with `adapter.quote()` to improve cross-database compatibility in dbt models.
This change ensures that identifier quoting is handled correctly by the specific dbt adapter being used. Modified files primarily in `models/staging/synthea/` and `models/omop/` where identifiers were hard-quoted in `dbt.cast` calls or aliases.

Refactor: Use adapter.quote() for identifiers.

---

dbt_project.yml
models/intermediate/int__measurement_observations.sql
models/intermediate/int__source_to_standard_vocab_map.sql
models/omop/_models/measurement.yml
models/omop/source_to_concept_map.sql
models/staging/vocabulary/_vocabulary__model.yml
models/staging/vocabulary/_vocabulary__sources.yml
models/staging/vocabulary/stg_vocabulary__source_to_concept_map.sql
seeds/stcm/source_to_concept_map_seed.csv
tests/generic/concept_record_completeness.sql

- Adjust measurement unit concept ID completeness threshold to accommodate an unmappable concept in the source data
- Fix concept record completeness check (include concept ID 0 in all failures)
- Add source to concept map seed and related models to incorporate custom mappings for Synthea unit concepts

Adjust unit thresh. and fix concept check
